spring:
  application:
    # sets the name in Eureka & Zipkin
    name: ${springboot.app.name:weatherservice}
  zipkin:
    baseUrl: http://${zipkin.host:localhost}:9411/

server:
  port: 8095

soap:
  service:
    base:
      url: /soap
  messages:
    logging: true
    extract: true

cxf:
  servicelist:
    title: WeatherService - Shine baby, shine!

# Switch Eureka-Usage on & off
ribbon:
  eureka:
    enabled: enabled

# Increase the Hystrix timeout to 60s (globally)
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

eureka:
  client:
    serviceUrl:
      defaultZone: http://${registry.host:localhost}:${registry.port:8761}/eureka/
    healthcheck:
      enabled: true

# No ugly logging pollution, if Eureka isnÂ´t up or found
logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF