spring:
  application:
    # sets the name in Eureka & Zipkin
    name: ${springboot.app.name:weatherclient}

server:
  port: 8087

# Client only mode
endpoint:
  autoinit: false

weatherservice:
  host: localhost
  port: 8080